services:
  base:
    image: skyline
    build:
      context: .
      target: development

  uikit-react:
    image: skyline
    command: npm run dev --workspace=apps/uikit-react -- --host 0.0.0.0
    volumes:
      - .:/app
      - uikit_react_root_modules:/app/node_modules/
      - uikit_react_workspace_modules:/app/apps/uikit-react/node_modules/
    ports:
      - "3001:3001"

volumes:
  uikit_react_root_modules:
  uikit_react_workspace_modules:
